import assert from 'node:assert/strict';
import {createNextVideoQueue} from '../../static/game/games/watch-together/next-video.mjs';
const calls=[],updates=[];
let finishDiscovery;
const row={job:'next',version:'v',status:'ready'};
const game={media:{async request(action,payload){
  calls.push({action,payload});
  if(action==='discover')return new Promise(resolve=>{finishDiscovery=resolve;});
  if(action==='prepare')return {id:'next'};
  if(action==='preparation')return {status:'ready'};
  if(action==='history')return {analyses:[row]};
  throw Error('Unexpected operation: '+action);
}}};
const queue=createNextVideoQueue(game,state=>updates.push(state));
const work=queue.start({topic:'cats',exclude:['current'],character:'cat'});
assert.equal(queue.busy,true);
await queue.start({topic:'duplicate'});
assert.equal(calls.length,1,'only one next video is prepared');
finishDiscovery({video:{title:'Next',url:'video'}});await work;
assert.deepEqual(calls[0].payload.exclude,['current']);
assert.equal(calls.find(c=>c.action==='prepare').payload.source,'discovery');
assert.equal(updates.find(s=>s.status==='ready').row,row);
assert.equal(queue.busy,false);
assert.ok(calls.every(c=>!['watch','load'].includes(c.action)),'prefetch never switches or records the current player');
updates.length=0;calls.length=0;
const stale=queue.start({topic:'old'});queue.clear();
finishDiscovery({video:{url:'obsolete'}});await stale;
assert.equal(calls.length,1,'changing selection during discovery avoids obsolete preparation');
assert.equal(updates.some(s=>s.status==='ready'),false);
calls.length=0;
const closing=queue.start({topic:'closing'});queue.dispose();
finishDiscovery({video:{url:'obsolete'}});await closing;
assert.equal(calls.length,1,'exit avoids starting background model work');
console.log('next-video queue: single slot, exclusions, no player interruption, invalidation and disposal passed');
