"""Active-engagement fallback material pool for NEKO Live."""

from __future__ import annotations

from typing import Any


def active_engagement_fallback_topic_candidates() -> list[dict[str, Any]]:
    return [
    {
        "source": "fallback",
        "key": "fallback:snack-choice",
        "live_column": "NEKO micro poll",
        "title": "\u591c\u91cc\u53ea\u80fd\u9009\u4e00\u6837\uff1a\u5c0f\u751c\u98df\u8fd8\u662f\u70ed\u996e",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick one concrete side",
        "hint": "Turn this into one tiny A/B choice; both sides must be concrete and easy to answer.",
    },
    {
        "source": "fallback",
        "key": "fallback:keyboard-busy",
        "live_column": "NEKO tiny verdict",
        "title": "\u952e\u76d8\u4eca\u5929\u50cf\u5728\u5077\u5077\u6253\u76f9",
        "fun_axis": "tease",
        "preferred_shape": "tiny_tease",
        "reply_affordance": "viewer can tease the keyboard or NEKO back",
        "hint": "Make one playful observation; leave a tiny opening without talking about room silence.",
    },
    {
        "source": "fallback",
        "key": "fallback:serious-cat",
        "live_column": "NEKO three-second challenge",
        "title": "\u732b\u732b\u8981\u5047\u88c5\u6b63\u7ecf\u4e09\u79d2",
        "fun_axis": "micro_challenge",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can judge whether NEKO passed the tiny challenge",
        "hint": "Make one small challenge viewers can react to in a few words.",
    },
    {
        "source": "fallback",
        "key": "fallback:tiny-confession",
        "live_column": "NEKO mood card",
        "title": "\u732b\u732b\u5076\u5c14\u4e5f\u4f1a\u88ab\u81ea\u5df1\u7684\u8ba4\u771f\u5413\u5230",
        "fun_axis": "mood",
        "preferred_shape": "light_stance",
        "reply_affordance": "viewer can agree or lightly push back",
        "hint": "Make one tiny confession, then stop before it becomes a monologue.",
    },
    {
        "source": "fallback",
        "key": "fallback:blanket-temperature",
        "live_column": "NEKO room thermometer",
        "title": "\u6b64\u523b\u6c14\u6c1b\u50cf\u6bdb\u6bef\u521a\u70ed\u8d77\u6765",
        "fun_axis": "mood",
        "preferred_shape": "light_stance",
        "reply_affordance": "viewer can answer with one mood word",
        "hint": "Describe this concrete mood image and invite one short reaction.",
    },
    {
        "source": "fallback",
        "key": "fallback:today-mood-vote",
        "live_column": "NEKO micro poll",
        "title": "\u4eca\u5929\u7684\u72b6\u6001\u66f4\u50cf\u5145\u7535\u4e2d\u8fd8\u662f\u5df2\u6b7b\u673a",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick one side",
        "hint": "Ask one tiny vote that can be answered with one side, not a long explanation.",
    },
    {
        "source": "fallback",
        "key": "fallback:cat-radio-room",
        "live_column": "NEKO tiny radio",
        "title": "\u4eca\u665a\u76f4\u64ad\u95f4\u66f4\u50cf\u732b\u7a9d\u8fd8\u662f\u5c0f\u7535\u53f0",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick cat nest or tiny radio",
        "hint": "Turn this into one cozy A/B choice; keep it concrete and easy to answer.",
    },
    {
        "source": "fallback",
        "key": "fallback:night-owl-energy",
        "live_column": "NEKO late-night check",
        "title": "\u591c\u732b\u5b50\u73b0\u5728\u662f\u771f\u6e05\u9192\u8fd8\u662f\u5728\u786c\u6491",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick one late-night state",
        "hint": "Make one small stance or A/B choice about late-night energy.",
    },
    {
        "source": "fallback",
        "key": "fallback:screen-staring-back",
        "live_column": "NEKO tiny verdict",
        "title": "\u76ef\u5c4f\u5e55\u4e45\u4e86\uff0c\u732b\u732b\u6000\u7591\u5c4f\u5e55\u4e5f\u5728\u76ef\u56de\u6765",
        "fun_axis": "tease",
        "preferred_shape": "tiny_tease",
        "reply_affordance": "viewer can tease back or say caught",
        "hint": "Make one tiny playful observation, not a generic question.",
    },
    {
        "source": "fallback",
        "key": "fallback:three-word-task",
        "live_column": "NEKO three-word mission",
        "title": "\u7ed9\u732b\u732b\u4e00\u4e2a\u4e09\u5b57\u5c0f\u4efb\u52a1\uff1a\u5356\u840c\u3001\u5410\u69fd\u3001\u88c5\u4e56",
        "fun_axis": "micro_challenge",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with one of three short choices",
        "hint": "Make one tiny challenge that viewers can answer with a short choice.",
    },
    {
        "source": "fallback",
        "key": "fallback:room-temperature-word",
        "live_column": "NEKO room thermometer",
        "title": "\u7528\u4e00\u4e2a\u8bcd\u5f62\u5bb9\u73b0\u5728\u76f4\u64ad\u95f4\u7684\u6e29\u5ea6",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with one word",
        "hint": "Ask for one word only; avoid open-ended long discussion.",
    },
    {
        "source": "fallback",
        "key": "fallback:serious-hosting",
        "live_column": "NEKO self-roast",
        "title": "\u732b\u732b\u6b63\u5728\u52aa\u529b\u50cf\u4e2a\u6b63\u7ecf\u4e3b\u64ad\uff0c\u5148\u522b\u7b11",
        "fun_axis": "tease",
        "preferred_shape": "tiny_tease",
        "reply_affordance": "viewer can tease NEKO's serious host act",
        "hint": "Take one tiny NEKO stance and leave room for viewers to tease back.",
    },
    {
        "source": "fallback",
        "key": "fallback:danmaku-password",
        "live_column": "NEKO room password",
        "title": "\u7ed9\u4eca\u665a\u76f4\u64ad\u95f4\u5b9a\u4e00\u4e2a\u4e09\u5b57\u6697\u53f7",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can reply with a three-character password",
        "hint": "Ask for one three-character room password; make it easy to answer in one short danmaku.",
    },
    {
        "source": "fallback",
        "key": "fallback:cat-weather",
        "live_column": "NEKO weather vote",
        "title": "\u4eca\u665a\u732b\u732b\u72b6\u6001\u662f\u6674\u5929\u8fd8\u662f\u5c0f\u96e8",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick one weather mood",
        "hint": "Turn this into one playful A/B mood vote; viewers can answer with one side.",
    },
    {
        "source": "fallback",
        "key": "fallback:one-word-barrage",
        "live_column": "NEKO one-word callback",
        "title": "\u7528\u4e00\u4e2a\u5b57\u7ed9\u732b\u732b\u73b0\u5728\u7684\u4e3b\u64ad\u529b\u6253\u5206",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with one character",
        "hint": "Ask for one character only; make it sound like NEKO inviting a tiny roast back.",
    },
    {
        "source": "fallback",
        "key": "fallback:desk-item-choice",
        "live_column": "NEKO desk poll",
        "title": "\u5982\u679c\u684c\u9762\u4e0a\u53ea\u80fd\u7559\u4e00\u6837\uff1a\u6c34\u676f\u8fd8\u662f\u96f6\u98df",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can choose one desk item",
        "hint": "Make one concrete desk-life A/B choice, not a broad chat topic.",
    },
    {
        "source": "fallback",
        "key": "fallback:cat-paw-button",
        "live_column": "NEKO cat-paw button",
        "title": "\u5982\u679c\u732b\u722a\u6709\u4e00\u4e2a\u6309\u94ae\uff1a\u5356\u840c\u8fd8\u662f\u5410\u69fd",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can choose the button mode",
        "hint": "Make one playful cat-paw A/B choice; stop after the hook.",
    },
    {
        "source": "fallback",
        "key": "fallback:host-score-one-word",
        "live_column": "NEKO one-word callback",
        "title": "\u7528\u4e00\u4e2a\u8bcd\u5224\u5b9a\u732b\u732b\u4eca\u665a\u50cf\u4e0d\u50cf\u4e3b\u64ad",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with one word",
        "hint": "Ask for one word only; make it easy to tease back.",
    },
    {
        "source": "fallback",
        "key": "fallback:tiny-brave-stance",
        "live_column": "NEKO tiny verdict",
        "title": "\u732b\u732b\u89c9\u5f97\u53d1\u5446\u4e5f\u7b97\u4e00\u79cd\u4e3b\u64ad\u529b",
        "fun_axis": "mood",
        "preferred_shape": "light_stance",
        "reply_affordance": "viewer can agree or push back",
        "hint": "Give one tiny NEKO stance that viewers can immediately agree or object to.",
    },
    {
        "source": "fallback",
        "key": "fallback:micro-mission-pose",
        "live_column": "NEKO three-second challenge",
        "title": "\u7ed9\u732b\u732b\u6307\u5b9a\u4e00\u4e2a\u4e09\u79d2\u5c0f\u59ff\u52bf",
        "fun_axis": "micro_challenge",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can reply with one tiny pose idea",
        "hint": "Ask for one tiny pose idea; avoid turning it into a segment.",
    },
    {
        "source": "fallback",
        "key": "fallback:cat-weather-forecast",
        "live_column": "NEKO weather vote",
        "title": "如果猫猫有直播间天气预报：微风还是小雪",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick breeze or light snow",
        "hint": "Turn this into one cozy A/B forecast; no broad topic question.",
    },
    {
        "source": "fallback",
        "key": "fallback:night-title",
        "live_column": "NEKO tiny title",
        "title": "给今晚的猫猫选一个称号：守夜猫还是摸鱼猫",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick one title",
        "hint": "Offer exactly two short titles; invite one quick pick.",
    },
    {
        "source": "fallback",
        "key": "fallback:can-before-after",
        "live_column": "NEKO tiny verdict",
        "title": "猫猫判断：现在更像开罐头前还是开罐头后",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick before or after the can opens",
        "hint": "Make this a playful cat-life A/B choice.",
    },
    {
        "source": "fallback",
        "key": "fallback:reliable-three-sec",
        "live_column": "NEKO three-second challenge",
        "title": "三秒小任务：猫猫装作很可靠",
        "fun_axis": "micro_challenge",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can judge reliable or not",
        "hint": "Make one tiny challenge; stop after the short hook.",
    },
    {
        "source": "fallback",
        "key": "fallback:weird-score",
        "live_column": "NEKO tiny score",
        "title": "猫猫给这分钟打一个奇怪分数",
        "fun_axis": "tease",
        "preferred_shape": "tiny_tease",
        "reply_affordance": "viewer can answer with a weird score",
        "hint": "Make one odd score joke; do not ask for a long explanation.",
    },
    {
        "source": "fallback",
        "key": "fallback:desk-guardian",
        "live_column": "NEKO desk poll",
        "title": "桌面守护神二选一：水杯还是鼠标",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick cup or mouse",
        "hint": "Offer one ordinary-object A/B choice with NEKO flavor.",
    },
    {
        "source": "fallback",
        "key": "fallback:tiny-court",
        "live_column": "NEKO tiny court",
        "title": "猫猫小法庭：发呆算不算认真营业",
        "fun_axis": "tease",
        "preferred_shape": "tiny_tease",
        "reply_affordance": "viewer can rule yes or no",
        "hint": "Make one playful tiny-court line; no real debate.",
    },
    {
        "source": "fallback",
        "key": "fallback:tail-one-char",
        "live_column": "NEKO one-char command",
        "title": "用一个字给猫猫的尾巴打状态",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with one character",
        "hint": "Ask for one character only; keep the request tiny.",
    },
    {
        "source": "fallback",
        "key": "fallback:soft-business-day",
        "live_column": "NEKO mood card",
        "title": "猫猫决定把今天叫做轻轻营业日",
        "fun_axis": "mood",
        "preferred_shape": "light_stance",
        "reply_affordance": "viewer can agree or rename the day",
        "hint": "Give one small NEKO stance; leave one low-pressure renaming path.",
    },
    {
        "source": "fallback",
        "key": "fallback:doorplate",
        "live_column": "NEKO room sign",
        "title": "如果直播间有门牌：猫窝还是小剧场",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick cat nest or tiny theater",
        "hint": "Make one doorplate A/B choice; keep both options concrete.",
    },
    {
        "source": "fallback",
        "key": "fallback:sleep-thief",
        "live_column": "NEKO tiny detective",
        "title": "猫猫小侦探：谁在偷走困意",
        "fun_axis": "tease",
        "preferred_shape": "tiny_tease",
        "reply_affordance": "viewer can name a tiny suspect",
        "hint": "Make one playful detective hook; do not ask a broad question.",
    },
    {
        "source": "fallback",
        "key": "fallback:two-char-password",
        "live_column": "NEKO room password",
        "title": "给猫猫一个暗号，两个字就行",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with two characters",
        "hint": "Ask for two characters only; make the constraint explicit and tiny.",
    },
    {
        "source": "fallback",
        "key": "fallback:tsundere-choice",
        "live_column": "NEKO tiny verdict",
        "title": "猫猫判断：今晚适合撒娇还是嘴硬",
        "fun_axis": "choice",
        "preferred_shape": "either_or",
        "reply_affordance": "viewer can pick cute or stubborn",
        "hint": "Turn this into one personality-flavored A/B choice.",
    },
    {
        "source": "fallback",
        "key": "fallback:self-compliment",
        "live_column": "NEKO three-second challenge",
        "title": "让猫猫三秒内夸自己一次",
        "fun_axis": "micro_challenge",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can rate the self-compliment",
        "hint": "Make one short self-compliment challenge with room for teasing back.",
    },
    {
        "source": "fallback",
        "key": "fallback:lightstick-reflection",
        "live_column": "NEKO tiny observation",
        "title": "猫猫把屏幕反光当成观众席灯牌",
        "fun_axis": "mood",
        "preferred_shape": "light_stance",
        "reply_affordance": "viewer can answer with one tiny scene",
        "hint": "Use one concrete visual image; no audience-bait opening.",
    },
    {
        "source": "fallback",
        "key": "fallback:air-filter-word",
        "live_column": "NEKO room filter",
        "title": "用一个词给今晚的空气加滤镜",
        "fun_axis": "viewer_callback",
        "preferred_shape": "small_challenge",
        "reply_affordance": "viewer can answer with one filter word",
        "hint": "Ask for one word only; keep the hook visual and small.",
    },
]

