"""Idle-hosting material pool for NEKO Live."""

from __future__ import annotations

from typing import Any


def idle_hosting_beat_candidates() -> list[dict[str, Any]]:
    return [
        {
            "key": "idle:soft-observation",
            "live_column": "NEKO tiny radio",
            "shape": "soft_observation",
            "fun_axis": "mood",
            "title": "\u5b89\u9759\u7684\u76f4\u64ad\u95f4\u6c14\u6c1b",
            "hint": "Say one soft concrete observation, not a direct question.",
            "reply_affordance": "viewer can agree or answer with one small mood word",
        },
        {
            "key": "idle:tiny-choice",
            "live_column": "NEKO micro poll",
            "shape": "tiny_choice",
            "fun_axis": "choice",
            "title": "\u732b\u732b\u7ed9\u89c2\u4f17\u7684\u5c0f\u9009\u62e9",
            "hint": "Offer one tiny A/B choice viewers can answer in a few words.",
            "reply_affordance": "viewer can pick one concrete side",
        },
        {
            "key": "idle:light-tease",
            "live_column": "NEKO tiny verdict",
            "shape": "light_tease",
            "fun_axis": "tease",
            "title": "\u732b\u732b\u5f0f\u8f7b\u5410\u69fd",
            "hint": "Make one harmless NEKO-flavored tease about the current quiet mood.",
            "reply_affordance": "viewer can tease NEKO back in one short line",
        },
        {
            "key": "idle:small-mood",
            "live_column": "NEKO mood card",
            "shape": "small_mood",
            "fun_axis": "mood",
            "title": "\u732b\u732b\u73b0\u5728\u7684\u5c0f\u72b6\u6001",
            "hint": "Share one tiny NEKO mood line with a small opening for viewers.",
            "reply_affordance": "viewer can answer with one mood word",
        },
        {
            "key": "idle:one-word-call",
            "live_column": "NEKO one-word callback",
            "shape": "one_word_call",
            "fun_axis": "viewer_callback",
            "title": "\u7528\u4e00\u4e2a\u5b57\u7ed9\u73b0\u5728\u7684\u732b\u732b\u6253\u4e2a\u6807\u7b7e",
            "hint": "Ask for exactly one character or one word; make it playful, not needy.",
            "reply_affordance": "viewer can answer with one character or one word",
        },
        {
            "key": "idle:micro-challenge",
            "live_column": "NEKO three-second challenge",
            "shape": "micro_challenge",
            "fun_axis": "micro_challenge",
            "title": "\u732b\u732b\u5047\u88c5\u4e3b\u64ad\u529b\u6ee1\u683c\u4e09\u79d2",
            "hint": "Offer one tiny challenge viewers can answer or tease back in a few words.",
            "reply_affordance": "viewer can judge or tease the tiny challenge",
        },
        {
            "key": "idle:prop-choice",
            "live_column": "NEKO desk poll",
            "shape": "tiny_choice",
            "fun_axis": "choice",
            "title": "\u684c\u9762\u4e8c\u9009\u4e00\uff1a\u6c34\u676f\u8fd8\u662f\u96f6\u98df",
            "hint": "Offer one concrete A/B choice from ordinary stream-room objects.",
            "reply_affordance": "viewer can pick one ordinary object",
        },
        {
            "key": "idle:cat-radio",
            "live_column": "NEKO tiny radio",
            "shape": "soft_observation",
            "fun_axis": "mood",
            "title": "\u8fd9\u4e00\u5206\u949f\u50cf\u732b\u732b\u5c0f\u7535\u53f0\u7684\u7a7a\u62cd",
            "hint": "Make one cozy radio-like observation; keep the hook low-pressure and indirect.",
            "reply_affordance": "viewer can answer with one cozy mood or tiny scene",
        },
        {
            "key": "idle:screen-blink",
            "live_column": "NEKO tiny observation",
            "shape": "soft_observation",
            "fun_axis": "mood",
            "title": "\u5c4f\u5e55\u95ea\u4e00\u4e0b\u4e5f\u50cf\u5728\u548c\u732b\u732b\u70b9\u5934",
            "hint": "Make one tiny visual observation; do not turn it into a question.",
            "reply_affordance": "viewer can answer with one tiny scene or mood",
        },
        {
            "key": "idle:cat-paw-button",
            "live_column": "NEKO cat-paw button",
            "shape": "tiny_choice",
            "fun_axis": "choice",
            "title": "\u732b\u722a\u6309\u94ae\u4e8c\u9009\u4e00\uff1a\u5356\u840c\u8fd8\u662f\u5410\u69fd",
            "hint": "Offer one playful cat-paw A/B choice; both sides must be concrete.",
            "reply_affordance": "viewer can pick cute mode or roast mode",
        },
        {
            "key": "idle:three-word-password",
            "live_column": "NEKO room password",
            "shape": "one_word_call",
            "fun_axis": "viewer_callback",
            "title": "\u7ed9\u4eca\u665a\u732b\u732b\u5c0f\u76f4\u64ad\u5b9a\u4e00\u4e2a\u4e09\u5b57\u6697\u53f7",
            "hint": "Ask for one three-character password; make it playful and easy.",
            "reply_affordance": "viewer can answer with three characters",
        },
        {
            "key": "idle:serious-three-seconds",
            "live_column": "NEKO three-second challenge",
            "shape": "micro_challenge",
            "fun_axis": "micro_challenge",
            "title": "\u732b\u732b\u6311\u6218\u6b63\u7ecf\u4e3b\u6301\u4e09\u79d2",
            "hint": "Offer one tiny self-challenge; stop before it becomes a segment.",
            "reply_affordance": "viewer can judge whether NEKO stayed serious",
        },
        {
            "key": "idle:reverse-tease",
            "live_column": "NEKO self-roast",
            "shape": "light_tease",
            "fun_axis": "tease",
            "title": "\u732b\u732b\u5148\u88ab\u81ea\u5df1\u7684\u4e3b\u64ad\u529b\u5410\u69fd\u4e00\u4e0b",
            "hint": "Make one self-directed tease, not a tease at viewers.",
            "reply_affordance": "viewer can tease NEKO back gently",
        },
        {
            "key": "idle:temperature-word",
            "live_column": "NEKO room thermometer",
            "shape": "one_word_call",
            "fun_axis": "viewer_callback",
            "title": "\u7528\u4e00\u4e2a\u8bcd\u7ed9\u73b0\u5728\u76f4\u64ad\u95f4\u6d4b\u4e2a\u6e29\u5ea6",
            "hint": "Ask for one word only; keep it like a tiny room-temperature check.",
            "reply_affordance": "viewer can answer with one temperature or mood word",
        },
        {
            "key": "idle:quiet-stamp",
            "live_column": "NEKO tiny stamp",
            "shape": "small_mood",
            "fun_axis": "mood",
            "title": "猫猫给空气盖一枚安静章",
            "hint": "Make one tiny mood-stamp line; do not ask a broad question.",
            "reply_affordance": "viewer can answer with one stamp word",
        },
        {
            "key": "idle:corner-snack",
            "live_column": "NEKO tiny observation",
            "shape": "soft_observation",
            "fun_axis": "mood",
            "title": "屏幕角落像藏了一颗小鱼干",
            "hint": "Make one small visual joke; keep it concrete and short.",
            "reply_affordance": "viewer can answer with one tiny scene",
        },
        {
            "key": "idle:tail-state-choice",
            "live_column": "NEKO tail poll",
            "shape": "tiny_choice",
            "fun_axis": "choice",
            "title": "给此刻的猫猫选一个尾巴状态：竖起还是卷住",
            "hint": "Offer one tail-state A/B choice; both sides must be short.",
            "reply_affordance": "viewer can pick raised tail or curled tail",
        },
        {
            "key": "idle:steady-three-sec",
            "live_column": "NEKO three-second challenge",
            "shape": "micro_challenge",
            "fun_axis": "micro_challenge",
            "title": "猫猫三秒假装很稳",
            "hint": "Make one tiny self-challenge about staying composed; do not explain anything.",
            "reply_affordance": "viewer can judge whether NEKO stayed steady",
        },
        {
            "key": "idle:keyboard-patrol",
            "live_column": "NEKO tiny patrol",
            "shape": "soft_observation",
            "fun_axis": "tease",
            "title": "今晚的键盘像在偷偷巡逻",
            "hint": "Make one playful object observation; do not turn it into a topic survey.",
            "reply_affordance": "viewer can tease the keyboard or NEKO",
        },
        {
            "key": "idle:one-char-command",
            "live_column": "NEKO one-char command",
            "shape": "one_word_call",
            "fun_axis": "viewer_callback",
            "title": "给猫猫一个一字指令：乖、凶、困",
            "hint": "Ask for exactly one character from the offered mood choices.",
            "reply_affordance": "viewer can answer with one character",
        },
        {
            "key": "idle:air-purr",
            "live_column": "NEKO tiny radio",
            "shape": "soft_observation",
            "fun_axis": "mood",
            "title": "猫猫把空拍听成小呼噜",
            "hint": "Make one cozy radio-like line; keep it as a mood, not a question.",
            "reply_affordance": "viewer can answer with one cozy sound or mood",
        },
        {
            "key": "idle:half-open-drawer",
            "live_column": "NEKO room image",
            "shape": "small_mood",
            "fun_axis": "mood",
            "title": "此刻直播间像半开的抽屉",
            "hint": "Use this as one odd but concrete room image.",
            "reply_affordance": "viewer can answer with one object or mood word",
        },
        {
            "key": "idle:unreliable-award",
            "live_column": "NEKO tiny award",
            "shape": "light_tease",
            "fun_axis": "tease",
            "title": "猫猫给自己颁一个不太靠谱奖",
            "hint": "Make one self-roast award line; do not announce a full ceremony.",
            "reply_affordance": "viewer can name or tease the award",
        },
        {
            "key": "idle:light-filter-word",
            "live_column": "NEKO room filter",
            "shape": "one_word_call",
            "fun_axis": "viewer_callback",
            "title": "让猫猫用一个词形容现在的灯光",
            "hint": "Ask for one filter word only; make the reply path tiny.",
            "reply_affordance": "viewer can answer with one light or color word",
        },
    ]


