"""Load and validate NEKO auto-rig packages generated by this plugin."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .export import AUTO_RIG_DIR_NAME, AUTO_RIG_MODEL_NAME

AUTO_RIG_FORMAT = "neko.live2d_auto_layer.auto_rig.v1"


def load_auto_rig_model(session_dir: str | Path) -> dict[str, object]:
    """Load a generated AutoRig model from a session directory."""
    session_path = Path(session_dir).resolve()
    rig_dir = (session_path / AUTO_RIG_DIR_NAME).resolve()
    model_path = (rig_dir / AUTO_RIG_MODEL_NAME).resolve()
    if not model_path.is_file():
        raise FileNotFoundError(f"AutoRig model not found: {model_path}")
    if rig_dir.parent != session_path:
        raise ValueError("AutoRig directory resolves outside session directory")

    model = _read_model(model_path)
    _validate_model(model, model_path=model_path)
    layers = _resolve_layers(model, rig_dir=rig_dir)
    preview_path = _resolve_optional_file(rig_dir, str(model.get("preview") or ""))

    return {
        "session_id": str(model.get("session_id") or session_path.name),
        "format": model["format"],
        "version": model["version"],
        "model_path": str(model_path),
        "auto_rig_dir": str(rig_dir),
        "canvas_size": model["canvas_size"],
        "coordinate_space": model.get("coordinate_space", "pixel_top_left"),
        "preview_path": str(preview_path) if preview_path else "",
        "parameters": model.get("parameters", []),
        "layers": layers,
        "quality": model.get("quality", {}),
        "quality_summary": _quality_summary(model),
    }


def _read_model(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"AutoRig model JSON is invalid: {path}") from exc
    if not isinstance(data, dict):
        raise ValueError("AutoRig model JSON must be an object")
    return data


def _validate_model(model: dict[str, Any], *, model_path: Path) -> None:
    if model.get("format") != AUTO_RIG_FORMAT:
        raise ValueError(f"Unsupported AutoRig format in {model_path}: {model.get('format')}")
    if int(model.get("version") or 0) != 1:
        raise ValueError(f"Unsupported AutoRig version in {model_path}: {model.get('version')}")
    canvas_size = model.get("canvas_size")
    if (
        not isinstance(canvas_size, list)
        or len(canvas_size) != 2
        or int(canvas_size[0]) <= 0
        or int(canvas_size[1]) <= 0
    ):
        raise ValueError("AutoRig model canvas_size must be [width, height]")
    layers = model.get("layers")
    if not isinstance(layers, list) or not layers:
        raise ValueError("AutoRig model must contain at least one layer")


def _resolve_layers(model: dict[str, Any], *, rig_dir: Path) -> list[dict[str, object]]:
    resolved: list[dict[str, object]] = []
    raw_layers = model.get("layers")
    if not isinstance(raw_layers, list):
        return resolved
    for raw_layer in sorted(
        (layer for layer in raw_layers if isinstance(layer, dict)),
        key=lambda layer: int(layer.get("draw_order") or 0),
    ):
        texture = str(raw_layer.get("texture") or "")
        texture_path = _resolve_required_file(rig_dir, texture)
        layer = dict(raw_layer)
        layer["texture_path"] = str(texture_path)
        resolved.append(layer)
    return resolved


def _resolve_required_file(root: Path, relative_path: str) -> Path:
    path = _resolve_optional_file(root, relative_path)
    if path is None:
        raise FileNotFoundError(f"AutoRig referenced file was not found: {relative_path}")
    return path


def _resolve_optional_file(root: Path, relative_path: str) -> Path | None:
    if not relative_path:
        return None
    candidate = (root / relative_path).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"AutoRig path resolves outside model directory: {relative_path}") from exc
    if not candidate.is_file():
        return None
    return candidate


def _quality_summary(model: dict[str, Any]) -> dict[str, object]:
    quality = model.get("quality")
    if not isinstance(quality, dict):
        return {}
    summary = quality.get("summary")
    return dict(summary) if isinstance(summary, dict) else {}
