"""Timeout budgets shared by the public-knowledge proxy chain."""

from knowledge._mutation_lock import MUTATION_LOCK_TIMEOUT_SECONDS


KNOWLEDGE_GET_TIMEOUT_SECONDS = 15.0
KNOWLEDGE_PLUGIN_TO_MAIN_MUTATION_TIMEOUT_SECONDS = (
    MUTATION_LOCK_TIMEOUT_SECONDS + 10.0
)
KNOWLEDGE_MAIN_TO_PLUGIN_MUTATION_TIMEOUT_SECONDS = (
    KNOWLEDGE_PLUGIN_TO_MAIN_MUTATION_TIMEOUT_SECONDS + 5.0
)
KNOWLEDGE_BROWSER_MUTATION_TIMEOUT_SECONDS = (
    KNOWLEDGE_MAIN_TO_PLUGIN_MUTATION_TIMEOUT_SECONDS + 5.0
)

assert (
    MUTATION_LOCK_TIMEOUT_SECONDS
    < KNOWLEDGE_PLUGIN_TO_MAIN_MUTATION_TIMEOUT_SECONDS
    < KNOWLEDGE_MAIN_TO_PLUGIN_MUTATION_TIMEOUT_SECONDS
    < KNOWLEDGE_BROWSER_MUTATION_TIMEOUT_SECONDS
)
