"""Internal extension decorator building blocks."""

from plugin.sdk_v2.shared.core.decorators import (
    CHECKPOINT_ATTR,
    EVENT_META_ATTR,
    HOOK_META_ATTR,
    PERSIST_ATTR,
    EntryKind,
    EventDecoratorMeta,
    HookDecoratorMeta,
    after_entry,
    around_entry,
    before_entry,
    custom_event,
    hook,
    lifecycle,
    message,
    neko_plugin,
    on_event,
    plugin,
    plugin_entry,
    replace_entry,
    timer_interval,
)

__all__ = [
    "EntryKind",
    "PERSIST_ATTR",
    "CHECKPOINT_ATTR",
    "EVENT_META_ATTR",
    "HOOK_META_ATTR",
    "EventDecoratorMeta",
    "HookDecoratorMeta",
    "neko_plugin",
    "on_event",
    "plugin_entry",
    "lifecycle",
    "message",
    "timer_interval",
    "custom_event",
    "hook",
    "before_entry",
    "after_entry",
    "around_entry",
    "replace_entry",
    "plugin",
]
