from __future__ import annotations

import pytest

from plugin.tests.unit.plugins import test_pomodoro_timer as _pomodoro_tests
from plugin.tests.unit.plugins import test_study_habit_store as _habit_tests

pytestmark = pytest.mark.unit

test_store_transaction_rolls_back_and_json_loads_is_public = (
    _habit_tests.test_store_transaction_rolls_back_and_json_loads_is_public
)
test_store_purge_all_clears_user_data_tables = (
    _habit_tests.test_store_purge_all_clears_user_data_tables
)
test_habit_store_creates_goals_and_cascades_focus_sessions = (
    _habit_tests.test_habit_store_creates_goals_and_cascades_focus_sessions
)
test_checkin_manager_tracks_streaks_makeups_and_session_derived_progress = _habit_tests.test_checkin_manager_tracks_streaks_makeups_and_session_derived_progress
test_habit_data_stays_out_of_public_knowledge_export = (
    _habit_tests.test_habit_data_stays_out_of_public_knowledge_export
)
test_checkin_streak_is_not_truncated_at_default_checked_dates_limit = (
    _habit_tests.test_checkin_streak_is_not_truncated_at_default_checked_dates_limit
)
test_memory_habit_bridge_updates_deck_goals_idempotently = (
    _habit_tests.test_memory_habit_bridge_updates_deck_goals_idempotently
)
test_memory_habit_bridge_summarizes_recitation_and_deck_focus = (
    _habit_tests.test_memory_habit_bridge_summarizes_recitation_and_deck_focus
)
test_memory_habit_bridge_reuses_existing_focus_goal_without_shrinking = (
    _habit_tests.test_memory_habit_bridge_reuses_existing_focus_goal_without_shrinking
)
test_memory_habit_bridge_summary_uses_configured_local_day = (
    _habit_tests.test_memory_habit_bridge_summary_uses_configured_local_day
)
test_memory_habit_bridge_summary_includes_due_only_decks = (
    _habit_tests.test_memory_habit_bridge_summary_includes_due_only_decks
)

test_pomodoro_timer_completes_focus_then_short_break_without_counting_break_minutes = _pomodoro_tests.test_pomodoro_timer_completes_focus_then_short_break_without_counting_break_minutes
test_pomodoro_timer_uses_long_break_interval_and_supports_cancel = (
    _pomodoro_tests.test_pomodoro_timer_uses_long_break_interval_and_supports_cancel
)
test_pomodoro_stop_completes_expired_focus_before_cancelling = (
    _pomodoro_tests.test_pomodoro_stop_completes_expired_focus_before_cancelling
)
test_pomodoro_stop_is_noop_when_timer_is_not_active = (
    _pomodoro_tests.test_pomodoro_stop_is_noop_when_timer_is_not_active
)
test_pomodoro_timer_respects_disabled_session_derived_checkins = (
    _pomodoro_tests.test_pomodoro_timer_respects_disabled_session_derived_checkins
)
test_pomodoro_timer_uses_configured_timezone_for_session_derived_checkins = _pomodoro_tests.test_pomodoro_timer_uses_configured_timezone_for_session_derived_checkins
test_pomodoro_start_does_not_mutate_state_when_initial_persistence_fails = _pomodoro_tests.test_pomodoro_start_does_not_mutate_state_when_initial_persistence_fails
test_pomodoro_completion_does_not_duplicate_progress_when_checkin_retries = _pomodoro_tests.test_pomodoro_completion_does_not_duplicate_progress_when_checkin_retries
test_pomodoro_completion_stays_retryable_when_persistence_fails = (
    _pomodoro_tests.test_pomodoro_completion_stays_retryable_when_persistence_fails
)
