"""Unit tests for ``scripts/check_no_nonascii_asset_names.py``.

Three-pronged coverage:

1. Live-repo gate: run the real script against this tree. Exit must be 0.
   This is what fails CI the moment someone lands a bundled asset with a
   non-ASCII filename — the thing that silently breaks macOS Developer ID
   signing with "the sealed resource directory is invalid".

2. Detection logic: build a throwaway git repo plus a throwaway tar/zip and
   assert the collector finds offenders on both paths (git listing and
   archive members) while leaving ASCII names alone.

3. Ratchet semantics: new offenders fail, baselined ones do not, and a
   baseline entry whose file is gone is a note rather than a failure (so a
   PR that legitimately deletes an asset does not go red).
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = PROJECT_ROOT / "scripts" / "check_no_nonascii_asset_names.py"
BASELINE_PATH = PROJECT_ROOT / "scripts" / "nonascii_asset_baseline.txt"

# A real offender shape: truncated-transcript audio, the family that made
# this check necessary in the first place.
CJK_NAME = "七天前，我们.mp3"


def _load_script_module():
    """Import the checker as a module without ``scripts`` being a package."""
    spec = importlib.util.spec_from_file_location(
        "check_no_nonascii_asset_names", SCRIPT_PATH,
    )
    assert spec and spec.loader, f"failed to load spec for {SCRIPT_PATH}"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _init_repo(root: Path) -> None:
    """A minimal git repo — the checker asks git which files exist."""
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)


# ---------------------------------------------------------------------------
# 1. Live-repo gate
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_live_repo_passes() -> None:
    """Current tree must have no non-baselined non-ASCII bundled filename."""
    # 60s: the script is I/O bound (one `git ls-files`, a couple of archive
    # listings) and normally finishes well under 5s. The cap keeps CI from
    # hanging if an archive ever turns pathological.
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH)],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, (
        "new non-ASCII bundled asset filename(s) detected:\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


@pytest.mark.unit
def test_baseline_is_sorted_and_has_no_duplicates() -> None:
    """The baseline is regenerated by --update-baseline; keep it canonical.

    A hand-edited, out-of-order or duplicated baseline produces noisy diffs
    and makes "did this list shrink?" impossible to eyeball in review.
    """
    entries = [
        line.strip()
        for line in BASELINE_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    assert entries == sorted(entries), "baseline is not sorted"
    assert len(entries) == len(set(entries)), "baseline has duplicate entries"


# ---------------------------------------------------------------------------
# 2. Detection logic
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_collects_offender_from_git_listing(tmp_path: Path) -> None:
    """An untracked-but-not-ignored asset is caught before ``git add``."""
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")
    (assets / "plain.mp3").write_bytes(b"x")

    offenders, from_archives = module.collect_offenders(tmp_path)

    assert offenders == {f"static/audio/{CJK_NAME}"}
    assert from_archives == {}


@pytest.mark.unit
def test_non_ascii_directory_with_ascii_files_is_allowed(tmp_path: Path) -> None:
    """Only basenames matter — codesign derives the identifier from those.

    Verified against a real Developer ID certificate: a bundle containing
    ``MacOS/<cjk-dir>/plain_name.png`` seals as ``identifier "plain_name"``
    and passes ``codesign --verify --deep --strict``. Flagging such paths
    would be a failure nobody could act on.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    directory = tmp_path / "static" / "素材目录"
    directory.mkdir(parents=True)
    (directory / "plain_name.png").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)

    assert offenders == set()


@pytest.mark.unit
def test_ignores_paths_outside_bundled_roots(tmp_path: Path) -> None:
    """``tests/`` carries CJK fixture paths and never reaches the .app."""
    module = _load_script_module()
    _init_repo(tmp_path)
    outside = tmp_path / "tests" / "fixtures"
    outside.mkdir(parents=True)
    (outside / CJK_NAME).write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)

    assert offenders == set()


@pytest.mark.unit
def test_ignores_gitignored_build_output(tmp_path: Path) -> None:
    """Generated payload must not make the answer depend on build state."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / ".gitignore").write_text("static/generated/\n", encoding="utf-8")
    generated = tmp_path / "static" / "generated"
    generated.mkdir(parents=True)
    (generated / CJK_NAME).write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == set()

    # …but --include-untracked is exactly the "check what I just built" mode.
    offenders_walked, _ = module.collect_offenders(tmp_path, include_untracked=True)
    assert offenders_walked == {f"static/generated/{CJK_NAME}"}


@pytest.mark.unit
def test_collects_offender_inside_unpacked_archives(tmp_path: Path) -> None:
    """Members of assets/*.tar.gz and pngtuber-packs/*.zip count as bundled.

    Both are expanded into ``static/`` at build time, so a non-ASCII member
    reaches Contents/MacOS even though it never appears in the source tree.
    Offenders are reported at their post-unpack destination.
    """
    module = _load_script_module()
    _init_repo(tmp_path)

    payload = tmp_path / "payload.bin"
    payload.write_bytes(b"x")

    (tmp_path / "assets").mkdir()
    with tarfile.open(tmp_path / "assets" / "model.tar.gz", "w:gz") as tar:
        tar.add(payload, arcname=f"model/expressions/{CJK_NAME}")
        tar.add(payload, arcname="model/model.moc3")

    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    with zipfile.ZipFile(packs / "tuber.zip", "w") as archive:
        archive.writestr(f"layers/{CJK_NAME}", "x")
    # unpack_builtin_pngtuber.py drives off this manifest: each listed archive
    # is expanded under its own `folder`, which is where members really land.
    (packs / "manifest.json").write_text(
        json.dumps({"models": [{"folder": "tuber", "archive": "tuber.zip"}]}),
        encoding="utf-8",
    )

    offenders, from_archives = module.collect_offenders(tmp_path)

    assert offenders == {
        f"static/model/expressions/{CJK_NAME}",
        f"static/pngtuber/tuber/layers/{CJK_NAME}",
    }
    assert from_archives[f"static/model/expressions/{CJK_NAME}"] == (
        "assets/model.tar.gz"
    )
    assert from_archives[f"static/pngtuber/tuber/layers/{CJK_NAME}"] == (
        "frontend/pngtuber-packs/tuber.zip"
    )


# ---------------------------------------------------------------------------
# 3. Ratchet semantics
# ---------------------------------------------------------------------------


def _write_baseline(root: Path, entries: list[str]) -> None:
    """Seed a grandfathered baseline directly, the way a human would."""
    path = root / "scripts" / "nonascii_asset_baseline.txt"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# grandfathered\n" + "".join(f"{e}\n" for e in sorted(entries)),
        encoding="utf-8",
    )


def _run_in(root: Path, module, *argv: str) -> int:
    """Run ``main`` with the module repointed at a throwaway tree."""
    module.REPO_ROOT = root
    module.BASELINE_PATH = root / "scripts" / "nonascii_asset_baseline.txt"
    return module.main(list(argv))


@pytest.mark.unit
def test_new_offender_fails_but_baselined_one_passes(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "scripts").mkdir()
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")

    # No baseline yet -> the file is new -> fail, with the codesign rationale
    # spelled out rather than a bare path.
    assert _run_in(tmp_path, module) == 1
    captured = capsys.readouterr()
    assert f"static/audio/{CJK_NAME}" in captured.out
    assert "NONASCII_ASSET_NAME" in captured.out
    assert "sealed resource directory is invalid" in captured.err

    # Grandfathering is a deliberate, hand-written act — --update-baseline
    # refuses to do it (see test_update_baseline_only_ever_shrinks).
    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    assert _run_in(tmp_path, module) == 0

    # A second offender still fails even though the first is baselined.
    (assets / f"another-{CJK_NAME}").write_bytes(b"x")
    assert _run_in(tmp_path, module) == 1


@pytest.mark.unit
def test_stale_baseline_entry_is_a_note_not_a_failure(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Deleting a grandfathered asset is progress; it must not go red."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "scripts").mkdir()
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    offender = assets / CJK_NAME
    offender.write_bytes(b"x")

    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    offender.unlink()

    assert _run_in(tmp_path, module) == 0
    captured = capsys.readouterr()
    assert "--update-baseline" in captured.err
    assert f"static/audio/{CJK_NAME}" in captured.err


@pytest.mark.unit
def test_update_baseline_refuses_build_dependent_input(tmp_path: Path) -> None:
    """A baseline seeded from local build output would differ per machine."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "scripts").mkdir()

    assert _run_in(tmp_path, module, "--update-baseline", "--include-untracked") == 2


@pytest.mark.unit
def test_update_baseline_only_ever_shrinks(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The documented command must not be a way to grandfather a new asset.

    Rewriting the baseline from the current tree would make `offenders -
    baseline` empty for a file added in the same PR, turning the ratchet into
    a rubber stamp.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    (assets / CJK_NAME).write_bytes(b"x")
    gone = f"static/audio/deleted-{CJK_NAME}"
    _write_baseline(tmp_path, [gone])

    assert _run_in(tmp_path, module, "--update-baseline") == 1
    captured = capsys.readouterr()
    assert "may only shrink" in captured.err
    assert f"static/audio/{CJK_NAME}" in captured.err

    # The vanished entry is still dropped — shrinking is the whole point —
    # but the new offender was not written, so the tree stays red.
    baseline = module.load_baseline(tmp_path / "scripts" / "nonascii_asset_baseline.txt")
    assert baseline == set()
    assert _run_in(tmp_path, module) == 1


@pytest.mark.unit
def test_baseline_growth_against_base_ref_fails(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Hand-editing the baseline is caught by the diff against the merge base.

    --update-baseline refusing to add is only half the ratchet; a contributor
    can still type the line by hand. Comparing with the base ref is what makes
    "only shrinks" actually true.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    assets = tmp_path / "static" / "audio"
    assets.mkdir(parents=True)
    _write_baseline(tmp_path, [])
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "base"],
        cwd=tmp_path,
        check=True,
    )

    # Add the asset AND the matching baseline line — the in-tree comparison
    # alone sees nothing wrong.
    (assets / CJK_NAME).write_bytes(b"x")
    _write_baseline(tmp_path, [f"static/audio/{CJK_NAME}"])
    assert _run_in(tmp_path, module) == 0

    assert _run_in(tmp_path, module, "--base", "HEAD") == 1
    captured = capsys.readouterr()
    assert f"+ static/audio/{CJK_NAME}" in captured.err

    # Shrinking against the same base ref stays green.
    _write_baseline(tmp_path, [])
    assert _run_in(tmp_path, module, "--base", "HEAD") == 1  # asset now unbaselined
    (assets / CJK_NAME).unlink()
    assert _run_in(tmp_path, module, "--base", "HEAD") == 0


@pytest.mark.unit
def test_missing_baseline_at_base_ref_is_not_growth(tmp_path: Path) -> None:
    """First landing of this check: the base ref has no baseline to diff."""
    module = _load_script_module()
    _init_repo(tmp_path)
    (tmp_path / "static").mkdir()
    (tmp_path / "static" / "ok.txt").write_bytes(b"x")
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "base"],
        cwd=tmp_path,
        check=True,
    )
    _write_baseline(tmp_path, ["static/audio/whatever.mp3"])

    assert _run_in(tmp_path, module, "--base", "HEAD") == 0


@pytest.mark.unit
def test_tar_hard_link_member_counts_as_extracted(tmp_path: Path) -> None:
    """`tar -xzm` materializes hard links, so their names reach the payload.

    TarInfo.isfile() is False for a hard-link entry, which used to hide a
    non-ASCII name that the build nevertheless writes into static/.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    payload = tmp_path / "payload.bin"
    payload.write_bytes(b"x")

    (tmp_path / "assets").mkdir()
    with tarfile.open(tmp_path / "assets" / "model.tar.gz", "w:gz") as tar:
        tar.add(payload, arcname="model/real.png")
        link = tarfile.TarInfo(f"model/{CJK_NAME}")
        link.type = tarfile.LNKTYPE
        link.linkname = "model/real.png"
        tar.addfile(link)

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"static/model/{CJK_NAME}"}


@pytest.mark.unit
def test_zip_outside_the_pngtuber_manifest_is_ignored(tmp_path: Path) -> None:
    """Only manifest-listed packs are unpacked; the rest ship opaque."""
    module = _load_script_module()
    _init_repo(tmp_path)
    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    with zipfile.ZipFile(packs / "unused.zip", "w") as archive:
        archive.writestr(f"layers/{CJK_NAME}", "x")
    (packs / "manifest.json").write_text(json.dumps({"models": []}), encoding="utf-8")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == set()


@pytest.mark.unit
def test_only_the_packaged_docs_subtree_is_scanned(tmp_path: Path) -> None:
    """The build packs docs/zh-CN/guide, not docs/ — no false positives."""
    module = _load_script_module()
    _init_repo(tmp_path)
    packaged = tmp_path / "docs" / "zh-CN" / "guide"
    packaged.mkdir(parents=True)
    (packaged / f"{CJK_NAME}.md").write_bytes(b"x")
    elsewhere = tmp_path / "docs" / "design"
    elsewhere.mkdir(parents=True)
    (elsewhere / f"{CJK_NAME}.md").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"docs/zh-CN/guide/{CJK_NAME}.md"}


@pytest.mark.unit
def test_model_manifest_filename_is_checked_without_a_build(tmp_path: Path) -> None:
    """The .onnx weights are gitignored; the name that will be written is not.

    Both manifest shapes are covered: `filename` at the top level and inside an
    `assets` list. Without this, the two model roots would only pay off under
    --include-untracked, which CI never runs.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    for rel in module.MODEL_MANIFESTS:
        (tmp_path / rel).parent.mkdir(parents=True, exist_ok=True)
    top_level, nested = module.MODEL_MANIFESTS[1], module.MODEL_MANIFESTS[0]
    (tmp_path / top_level).write_text(
        json.dumps({"filename": f"{CJK_NAME}.onnx"}), encoding="utf-8"
    )
    (tmp_path / nested).write_text(
        json.dumps({"assets": [{"filename": "ascii.onnx"}, {"filename": f"x{CJK_NAME}.onnx"}]}),
        encoding="utf-8",
    )

    offenders, from_archives = module.collect_offenders(tmp_path)

    top_dir = str(Path(top_level).parent).replace("\\", "/")
    nested_dir = str(Path(nested).parent).replace("\\", "/")
    assert offenders == {
        f"{top_dir}/{CJK_NAME}.onnx",
        f"{nested_dir}/x{CJK_NAME}.onnx",
    }
    assert from_archives[f"{top_dir}/{CJK_NAME}.onnx"] == top_level


@pytest.mark.unit
def test_malformed_manifest_is_a_loud_error(tmp_path: Path) -> None:
    """"No packs found" and "the manifest is a list" must not look the same."""
    module = _load_script_module()
    _init_repo(tmp_path)
    packs = tmp_path / "frontend" / "pngtuber-packs"
    packs.mkdir(parents=True)
    (packs / "manifest.json").write_text(json.dumps([{"folder": "x"}]), encoding="utf-8")

    with pytest.raises(SystemExit) as excinfo:
        module.collect_offenders(tmp_path)
    assert excinfo.value.code == 2

    (packs / "manifest.json").write_text(json.dumps({"models": "nope"}), encoding="utf-8")
    with pytest.raises(SystemExit) as excinfo:
        module.collect_offenders(tmp_path)
    assert excinfo.value.code == 2


@pytest.mark.unit
def test_unresolvable_base_ref_fails_instead_of_passing(tmp_path: Path) -> None:
    """A ref that cannot be resolved must not read as "the baseline didn't grow".

    Otherwise a shallow clone that never fetched origin/main turns the ratchet
    green exactly when it is supposed to bite.
    """
    module = _load_script_module()
    _init_repo(tmp_path)
    _write_baseline(tmp_path, ["static/audio/whatever.mp3"])

    # SystemExit(2), like the other environment failures in this script
    # (unreadable git listing, malformed manifest) — not a lint verdict.
    with pytest.raises(SystemExit) as excinfo:
        _run_in(tmp_path, module, "--base", "origin/nope")
    assert excinfo.value.code == 2


@pytest.mark.unit
def test_only_the_packaged_frontend_output_is_scanned(tmp_path: Path) -> None:
    """All three build scripts pack frontend/plugin-manager/dist and nothing else."""
    module = _load_script_module()
    _init_repo(tmp_path)
    source = tmp_path / "frontend" / "plugin-manager" / "src"
    source.mkdir(parents=True)
    (source / f"{CJK_NAME}.vue").write_bytes(b"x")
    packaged = tmp_path / "frontend" / "plugin-manager" / "dist" / "assets"
    packaged.mkdir(parents=True)
    (packaged / f"{CJK_NAME}.js").write_bytes(b"x")

    offenders, _ = module.collect_offenders(tmp_path)
    assert offenders == {f"frontend/plugin-manager/dist/assets/{CJK_NAME}.js"}
